title: The Indian Sonic Research Organisation
description: A sound research and experimental space
author: theisro
url: http://theisro.github.io/
excerpt_separator: <!--more-->
paginate: 3
paginate_path: /page/:num/

exclude: [
    'Makefile',
    'Gemfile',
    'Gemfile.lock',
    'README.md',
    'CNAME'
]

sass:
    sass_dir: assets/css

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
